### ISSUE TITLE
Mistyped link

### ISSUE THREAD

**Issue by bakomate2** [Lin-Buo-Ren/speedtest-cli-snap#5]
It's not with the snap, but at the Manjaro add remove software the link for the issues section is wrong. 
![Screenshot_20210811_213116](https://user-images.githubusercontent.com/60980497/129091462-dfccf47a-5734-499d-a59b-885712178a50.png)
The link are invalid, it should be with the 's' at the end. (https://github.com/Lin-Buo-Ren/speedtest-cli-snap/issues, not issue)

**Comment by brlin-tw** [comment]
Thanks for your report, I'll fix it as soon as possible.

**Comment by brlin-tw** [comment]
I've updated the description in the store backstage, thanks for your heads-up.
